// Ported from the classic client's client/src/utils/swatch/index.ts (#415 step 3).
// 3D-printable filament swatch generation. The swatch is a small card meant to
// be printed in the filament itself, carrying the same info as the printed
// labels (vendor, name, material, temperatures, id) plus a Spoolman QR code.
// The text/QR form a raised one-layer marking whose triangles are face-colored
// black or white — whichever contrasts best with the filament color — so it
// can be printed with a filament change at the last layer, or mapped to a
// second filament by slicers that import 3MF face colors (e.g. Bambu Studio).
//
// Adapted for client_v2: the classic client's `swatchInputFromFilament` took a
// React `IFilament`; this version takes client_v2's `Filament` view model
// ($lib/types) instead. See swatchInputFromFilament below for the field
// mapping and its deviations from the classic version (missing/zero
// temperatures, color hex format).

import type { Filament } from '$lib/types';
import type { SwatchInput } from './layout';
import { buildSwatchLayoutForStyle, getSwatchStyle } from './styles';
import { buildSwatch3mf } from './threeMf';

export { pickMarkingColor } from './color';
export type { MarkingColor } from './color';
export { buildSwatchLayout } from './layout';
export type {
	MarkRect,
	SwatchHangerTab,
	SwatchHole,
	SwatchInput,
	SwatchLayout,
	SwatchStyleSpec,
	SwatchTextLine
} from './layout';
export { buildSwatchLayoutForStyle, DEFAULT_SWATCH_STYLE_KEY, getSwatchStyle, SWATCH_STYLES } from './styles';
export type { SwatchStyle } from './styles';
export { buildSwatch3mf, buildSwatchMeshes } from './threeMf';

/** A positive, finite temperature in Celsius, or undefined if unset/invalid. */
function definedTemp(value: number | undefined): number | undefined {
	return value !== undefined && Number.isFinite(value) && value > 0 ? value : undefined;
}

/**
 * What client_v2's `mapFilament` shows for a filament that has no name. It is a screen label,
 * not a name, so it must not be printed on the card: the classic client leaves the name line
 * out and titles the card by its vendor, and so does this.
 */
const UNNAMED = '(unnamed filament)';

/**
 * client_v2 stores colors as "#rrggbb" (see colorsFromApi in $lib/api/map.ts),
 * while the classic client passed color_hex values as stored by the API,
 * without the leading "#". Strip it here so the swatch gets exactly the
 * format the classic client passed (color.ts accepts either, but this keeps
 * the mapping byte-for-byte equivalent to the classic behaviour).
 */
function stripHash(hex: string): string {
	return hex.replace(/^#/, '');
}

export function swatchInputFromFilament(
	filament: Filament,
	options: { qrPayload: string; vendorName?: string }
): SwatchInput {
	return {
		id: Number(filament.id),
		name: filament.name && filament.name !== UNNAMED ? filament.name : undefined,
		vendorName: options.vendorName,
		material: filament.material || undefined,
		diameterMm: filament.diameter,
		weightG: filament.weight,
		// client_v2 maps a missing temperature to 0; treat 0 (and any other
		// non-positive or non-finite value) as unset, as the classic client
		// omits the temperature line entirely when the field is missing.
		extruderTempC: definedTemp(filament.nozzleTemp),
		bedTempC: definedTemp(filament.bedTemp),
		articleNumber: filament.articleNumber || undefined,
		colorHexes: filament.colors.map(stripHash),
		qrPayload: options.qrPayload
	};
}

/** Human-readable swatch title, used for the 3MF metadata and object name. */
export function swatchTitle(input: SwatchInput): string {
	const name = [input.vendorName, input.name].filter(Boolean).join(' ');
	return name !== '' ? name : `Filament #${input.id}`;
}

function sanitizeFilenamePart(part: string): string {
	return part.replace(/\s+/g, '_').replace(/[^A-Za-z0-9._-]/g, '');
}

export function swatchFilename(input: SwatchInput, styleKey?: string | null): string {
	const parts = [`swatch_${getSwatchStyle(styleKey).key}_${input.id}`, input.vendorName, input.name]
		.filter((part): part is string => Boolean(part))
		.map(sanitizeFilenamePart)
		.filter((part) => part !== '');
	return `${parts.join('_')}.3mf`;
}

/** Generate the downloadable 3MF for a filament, using the given (or default) swatch style. */
export function generateFilamentSwatch(
	input: SwatchInput,
	styleKey?: string | null
): { data: Uint8Array; filename: string } {
	const layout = buildSwatchLayoutForStyle(input, styleKey);
	const data = buildSwatch3mf(layout, {
		title: `${swatchTitle(input)} swatch`,
		description:
			'Filament swatch generated by Spoolman. Print the card in the filament itself; ' +
			`the raised ${layout.markingThicknessMm} mm text/QR marking is meant to be printed in ${layout.markingColor} ` +
			'(add a filament change at the last layer, or import the embedded face colors in a multi-color slicer).'
	});
	return { data, filename: swatchFilename(input, styleKey) };
}

/** Trigger a browser download of binary data. */
export function saveBinaryFile(data: Uint8Array, filename: string, mimeType = 'model/3mf'): void {
	const blob = new Blob([new Uint8Array(data)], { type: mimeType });
	const url = URL.createObjectURL(blob);
	const anchor = document.createElement('a');
	anchor.href = url;
	anchor.download = filename;
	document.body.appendChild(anchor);
	anchor.click();
	anchor.remove();
	URL.revokeObjectURL(url);
}
