"""Generate slicer-native filament profiles from Spoolman filament data (#76).

Pure, dependency-free serializers for the three most-requested slicer ecosystems:

- PrusaSlicer / SuperSlicer filament config (``.ini``)
- OrcaSlicer / Bambu Studio filament preset (``.json``)
- Cura material (``.xml.fdm_material``)

Only the fields Spoolman actually tracks are emitted; anything a slicer needs beyond that is left to
the slicer's own defaults, and unknown temperatures/costs are simply omitted rather than guessed. The
functions read plain attributes off a filament-like object (the ORM ``Filament`` in production, a
lightweight stand-in in tests) so they can be unit-tested without a database.
"""

from __future__ import annotations

import json
import uuid
from enum import Enum
from typing import TYPE_CHECKING
from xml.sax.saxutils import escape

if TYPE_CHECKING:
    from spoolman.database.models import Filament

# A fixed namespace so a given filament always maps to the same Cura material GUID across re-exports.
_CURA_GUID_NAMESPACE = uuid.UUID("1b4e28ba-2fa1-11d2-883f-0016d3cca427")
# PrusaSlicer/OrcaSlicer require a filament_type to load the preset; fall back to the commonest.
_DEFAULT_MATERIAL = "PLA"


class SlicerFormat(Enum):
    """The supported slicer profile formats."""

    prusa = "prusa"
    orca = "orca"
    cura = "cura"


def _profile_name(f: Filament) -> str:
    """Return a human-readable preset name: "Vendor Name", falling back to the filament name or id."""
    name = f.name or f"Filament {f.id}"
    vendor = getattr(f.vendor, "name", None) if f.vendor else None
    return f"{vendor} {name}" if vendor else name


def _safe_filename(name: str) -> str:
    """Reduce a preset name to a filesystem-safe base (alphanumerics, dash, underscore)."""
    cleaned = "".join(c if c.isalnum() or c in "-_" else "_" for c in name).strip("_")
    return cleaned or "filament"


def _color(f: Filament) -> str | None:
    """Return the colour as ``#RRGGBB`` (dropping any stored alpha), or None if unset."""
    if not f.color_hex:
        return None
    return f"#{f.color_hex[:6].upper()}"


def _nozzle_temp(f: Filament) -> int | None:
    """Preferred nozzle temperature: the explicit setting, else the mid-point of the range (#112)."""
    if f.settings_extruder_temp is not None:
        return f.settings_extruder_temp
    lo, hi = f.settings_extruder_temp_min, f.settings_extruder_temp_max
    if lo is not None and hi is not None:
        return round((lo + hi) / 2)
    return None


def _bed_temp(f: Filament) -> int | None:
    """Preferred bed temperature: the explicit setting, else the mid-point of the range (#112)."""
    if f.settings_bed_temp is not None:
        return f.settings_bed_temp
    lo, hi = f.settings_bed_temp_min, f.settings_bed_temp_max
    if lo is not None and hi is not None:
        return round((lo + hi) / 2)
    return None


def _cost_per_kg(f: Filament) -> float | None:
    """Spoolman prices a whole spool; slicers want cost per kg. None unless price and net weight known."""
    if f.price is None or not f.weight:
        return None
    return round(f.price * 1000.0 / f.weight, 4)


def _to_prusa(f: Filament) -> str:
    """PrusaSlicer / SuperSlicer filament config (INI)."""
    material = f.material or _DEFAULT_MATERIAL
    lines = [
        "# Generated by Spoolman",
        f"filament_type = {material}",
        f"filament_diameter = {f.diameter}",
        f"filament_density = {f.density}",
        f"filament_settings_id = {_profile_name(f)}",
    ]
    vendor = getattr(f.vendor, "name", None) if f.vendor else None
    if vendor:
        lines.append(f"filament_vendor = {vendor}")
    nozzle = _nozzle_temp(f)
    if nozzle is not None:
        lines.append(f"temperature = {nozzle}")
        lines.append(f"first_layer_temperature = {nozzle}")
    bed = _bed_temp(f)
    if bed is not None:
        lines.append(f"bed_temperature = {bed}")
        lines.append(f"first_layer_bed_temperature = {bed}")
    color = _color(f)
    if color is not None:
        lines.append(f"filament_colour = {color}")
    cost = _cost_per_kg(f)
    if cost is not None:
        lines.append(f"filament_cost = {cost}")
    return "\n".join(lines) + "\n"


def _to_orca(f: Filament) -> str:
    """OrcaSlicer / Bambu Studio filament preset (JSON). Most values are single-element string arrays."""
    material = f.material or _DEFAULT_MATERIAL
    preset: dict[str, object] = {
        "type": "filament",
        "name": _profile_name(f),
        "from": "User",
        "filament_type": [material],
        "filament_diameter": [str(f.diameter)],
        "filament_density": [str(f.density)],
    }
    vendor = getattr(f.vendor, "name", None) if f.vendor else None
    if vendor:
        preset["filament_vendor"] = [vendor]
    nozzle = _nozzle_temp(f)
    if nozzle is not None:
        preset["nozzle_temperature"] = [str(nozzle)]
        preset["nozzle_temperature_initial_layer"] = [str(nozzle)]
    bed = _bed_temp(f)
    if bed is not None:
        preset["hot_plate_temp"] = [str(bed)]
        preset["hot_plate_temp_initial_layer"] = [str(bed)]
    color = _color(f)
    if color is not None:
        preset["default_filament_colour"] = [color]
    cost = _cost_per_kg(f)
    if cost is not None:
        preset["filament_cost"] = [str(cost)]
    return json.dumps(preset, indent=4, ensure_ascii=False) + "\n"


def _to_cura(f: Filament) -> str:
    """Cura material (fdm_material XML). Cost lives in Cura's own material store, so it is not emitted."""
    material = f.material or _DEFAULT_MATERIAL
    vendor = (getattr(f.vendor, "name", None) if f.vendor else None) or "Spoolman"
    color_name = f.name or material
    guid = uuid.uuid5(_CURA_GUID_NAMESPACE, str(f.id))

    settings = []
    nozzle = _nozzle_temp(f)
    if nozzle is not None:
        settings.append(f'      <setting key="print temperature">{nozzle}</setting>')
    bed = _bed_temp(f)
    if bed is not None:
        settings.append(f'      <setting key="heated bed temperature">{bed}</setting>')
    settings_block = ("\n" + "\n".join(settings) + "\n    ") if settings else ""

    color_code = _color(f)
    color_line = f"\n    <color_code>{escape(color_code)}</color_code>" if color_code else ""

    return (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        '<fdmmaterial xmlns="http://www.ultimaker.com/material" version="1.3">\n'
        "  <metadata>\n"
        "    <name>\n"
        f"      <brand>{escape(vendor)}</brand>\n"
        f"      <material>{escape(material)}</material>\n"
        f"      <color>{escape(color_name)}</color>\n"
        "    </name>\n"
        f"    <GUID>{guid}</GUID>\n"
        "    <version>1</version>"
        f"{color_line}\n"
        "  </metadata>\n"
        "  <properties>\n"
        f"    <density>{f.density}</density>\n"
        f"    <diameter>{f.diameter}</diameter>\n"
        "  </properties>\n"
        f"  <settings>{settings_block}</settings>\n"
        "</fdmmaterial>\n"
    )


_MEDIA_TYPES = {
    SlicerFormat.prusa: "text/plain",
    SlicerFormat.orca: "application/json",
    SlicerFormat.cura: "application/xml",
}
_EXTENSIONS = {
    SlicerFormat.prusa: "ini",
    SlicerFormat.orca: "json",
    SlicerFormat.cura: "xml.fdm_material",
}
_GENERATORS = {
    SlicerFormat.prusa: _to_prusa,
    SlicerFormat.orca: _to_orca,
    SlicerFormat.cura: _to_cura,
}


def generate_slicer_profile(f: Filament, fmt: SlicerFormat) -> tuple[str, str, str]:
    """Return (filename, content, media_type) for a filament in the given slicer format."""
    content = _GENERATORS[fmt](f)
    filename = f"{_safe_filename(_profile_name(f))}.{_EXTENSIONS[fmt]}"
    return filename, content, _MEDIA_TYPES[fmt]
