// Vendors shared pure-TS modules from the web client into mobile/src/shared/.
//
// The app and the web client must agree on the scan-payload grammar, so the
// canonical source stays client/src/utils/scan.ts. Importing it directly is
// not possible in release builds: Metro refuses files outside the project
// root, and Expo CLI (SDK 57) recomputes watchFolders itself, ignoring what
// metro.config.js sets. So the file is copied in with a marker header, the
// copy is regenerated on every `npm install` (prepare script), and
// src/shared/drift.test.ts asserts the checked-in copy matches its source.
//
// Run manually with: npm run sync-shared

import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const mobileRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const repoRoot = path.resolve(mobileRoot, "..");

export const HEADER = `// AUTO-GENERATED by mobile/scripts/sync-shared.mjs — do not edit.
// Source of truth: %SOURCE% (edit there, then run \`npm run sync-shared\`;
// \`npm install\` also regenerates this file).

`;

export const SHARED_FILES = [
  {
    source: "client/src/utils/scan.ts",
    target: "src/shared/scan.ts",
  },
];

export function expectedContent({ source }) {
  const sourceText = readFileSync(path.join(repoRoot, source), "utf-8");
  return HEADER.replace("%SOURCE%", source) + sourceText;
}

export function targetPath({ target }) {
  return path.join(mobileRoot, target);
}

function main() {
  for (const file of SHARED_FILES) {
    const dest = targetPath(file);
    mkdirSync(path.dirname(dest), { recursive: true });
    writeFileSync(dest, expectedContent(file));
    console.log(`synced ${file.source} -> mobile/${file.target}`);
  }
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  main();
}
