// AUTO-GENERATED by mobile/scripts/sync-shared.mjs — do not edit.
// Source of truth: client/src/utils/scan.ts (edit there, then run `npm run sync-shared`;
// `npm install` also regenerates this file).

// Spoolman QR-code payload encode/decode, extracted from the scanner modal and the
// QR print dialogs so the two halves can be round-trip tested against each other
// (TESTING_STRATEGY.md — the encoder and decoder are independent code paths, so a
// build→parse round-trip is a genuine oracle).

export type ScanResource = "spool" | "filament" | "location";

export interface ScanTarget {
  resource: ScanResource;
  id: string;
  /** The in-app route to navigate to, e.g. "/spool/show/42". */
  path: string;
}

const PREFIX: Record<ScanResource, string> = { spool: "S", filament: "F", location: "L" };

/**
 * The reserved "clear the active spool" sentinel (#132). Spoolman itself has no notion of an active
 * spool — that state is owned by external consumers such as Moonraker — so this is purely a documented
 * convention so different integrations (barcode scanners feeding a printer, ESPHome bridges, …) agree
 * on one value instead of each inventing their own. The in-app scanner recognises it so it is
 * acknowledged rather than silently ignored.
 */
export const CLEAR_PAYLOAD = "WEB+SPOOLMAN:CLEAR";

/** Whether a scanned value is the reserved clear-spool sentinel (#132), case-insensitively. */
export function isClearScan(raw: string): boolean {
  return raw.trim().toLowerCase() === CLEAR_PAYLOAD.toLowerCase();
}

// Retail UPC/EAN/GTIN barcodes are all-digit strings of these fixed lengths (EAN-8, UPC-A/UPC-E→12,
// EAN-13, GTIN-14).
const RETAIL_BARCODE_LENGTHS = new Set([8, 12, 13, 14]);

/**
 * Whether an (unrecognised-as-Spoolman) scan looks like a manufacturer retail barcode (#97b), so it
 * can trigger an article-number lookup-or-create instead of being ignored. Pure and testable.
 */
export function looksLikeRetailBarcode(raw: string): boolean {
  const value = raw.trim();
  return /^[0-9]+$/.test(value) && RETAIL_BARCODE_LENGTHS.has(value.length);
}

/**
 * Build the QR payload for a spool/filament, matching what the print dialogs emit.
 *
 * With no baseUrl this yields the custom scheme `WEB+SPOOLMAN:S-<id>` / `...:F-<id>`.
 * With a baseUrl it yields the deep link `<baseUrl>/<resource>/show/<id>`.
 */
export function buildScanPayload(resource: ScanResource, id: number | string, baseUrl?: string): string {
  if (baseUrl) {
    return `${baseUrl}/${resource}/show/${id}`;
  }
  return `WEB+SPOOLMAN:${PREFIX[resource]}-${id}`;
}

const SPOOL_SCHEME = /^web\+spoolman:s-(?<id>[0-9]+)$/i;
const FILAMENT_SCHEME = /^web\+spoolman:f-(?<id>[0-9]+)$/i;
const LOCATION_SCHEME = /^web\+spoolman:l-(?<id>[0-9]+)$/i;
const SPOOL_URL = /^https?:\/\/[^/]+(?:\/[^/]+)*\/spool\/show\/(?<id>[0-9]+)$/i;
const FILAMENT_URL = /^https?:\/\/[^/]+(?:\/[^/]+)*\/filament\/show\/(?<id>[0-9]+)$/i;
const LOCATION_URL = /^https?:\/\/[^/]+(?:\/[^/]+)*\/location\/show\/(?<id>[0-9]+)$/i;

/**
 * Parse a scanned QR value into a navigation target, or null if it is not a
 * recognised Spoolman code. Accepts both the custom scheme and deep-link URL
 * forms, for spools, filaments and locations, case-insensitively. The URL form
 * tolerates a base path (any number of intermediate path segments) for sub-path
 * deploys. A scanned location resolves to its show page, which lists the spools
 * currently stored there (issue #90).
 */
export function parseScanResult(raw: string): ScanTarget | null {
  const spool = raw.match(SPOOL_SCHEME) ?? raw.match(SPOOL_URL);
  if (spool?.groups) {
    return { resource: "spool", id: spool.groups.id, path: `/spool/show/${spool.groups.id}` };
  }
  const filament = raw.match(FILAMENT_SCHEME) ?? raw.match(FILAMENT_URL);
  if (filament?.groups) {
    return { resource: "filament", id: filament.groups.id, path: `/filament/show/${filament.groups.id}` };
  }
  const location = raw.match(LOCATION_SCHEME) ?? raw.match(LOCATION_URL);
  if (location?.groups) {
    return { resource: "location", id: location.groups.id, path: `/location/show/${location.groups.id}` };
  }
  return null;
}
